# Generated by Django 5.2 on 2026-09-24 11:39

import app.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('course_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('markers', models.ManyToManyField(related_name='courses_marked', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('spec', models.FileField(blank=True, null=True, upload_to=app.models.rename_file('spec'))),
                ('rubric', models.FileField(blank=True, null=True, upload_to=app.models.rename_file('rubric'))),
                ('grade_moderation', models.CharField(blank=True, choices=[('linear', 'Linear'), ('z-score', 'Z-Score')], max_length=10, null=True)),
                ('grade_moderation_param_1', models.FloatField(blank=True, null=True)),
                ('grade_moderation_param_2', models.FloatField(blank=True, null=True)),
                ('feedback_tone', models.CharField(blank=True, choices=[('formal', 'Formal'), ('friendly', 'Friendly')], max_length=10, null=True)),
                ('feedback_length_min', models.PositiveIntegerField(blank=True, null=True)),
                ('feedback_length_max', models.PositiveIntegerField(blank=True, null=True)),
                ('feedback_moderation_requests', models.TextField(blank=True, null=True)),
                ('feedback_moderation_prompt', models.TextField(blank=True, null=True)),
                ('markers', models.ManyToManyField(related_name='assignments_marked', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course')),
            ],
            options={
                'unique_together': {('course', 'name')},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_marker', models.BooleanField(default=False)),
                ('is_course_lead', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MarkedSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_cid', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numeric characters are allowed.'), django.core.validators.MinLengthValidator(8)])),
                ('marker_grade', models.FloatField(blank=True, null=True)),
                ('initial_marker_feedback', models.TextField(blank=True, null=True)),
                ('improved_marker_feedback', models.TextField(blank=True, null=True)),
                ('moderated_grade', models.FloatField(blank=True, null=True)),
                ('moderated_feedback', models.TextField(blank=True, null=True)),
                ('suggested_improvements', models.TextField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.assignment')),
                ('marker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('assignment', 'student_cid', 'marker')},
            },
        ),
    ]
